language: python

virtualenv:
    system_site_packages: true

env:
    - PYTHON=2.7
    - PYTHON=3.3

before_install:
    - if [ "${PYTHON}" != "2.7" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
        export PATH=/home/$USER/anaconda/bin:$PATH;
        conda update --yes conda;
      fi;

install:
    # Install mnefun
    - python setup.py build
    - python setup.py install

script:
    - make flake
